package com.example.tests;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.ui.ExpectedConditions;
import java.time.Duration;
import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Recorded test: bestbuy-ps5-checkout
 * Base URL: https://www.bestbuy.com
 * Recorded at: 2026-03-08
 * Actions: 18
 *
 * Generated by selenium-intellij-mcp-server recording service
 *
 * Run:  mvn test -Dtest=BestBuyPS5RecordedTest
 */
public class BestBuyPS5RecordedTest {

    private WebDriver driver;
    private WebDriverWait wait;

    @BeforeEach
    public void setUp() {
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--start-maximized");
        options.addArguments("--disable-notifications");
        driver = new ChromeDriver(options);
        wait = new WebDriverWait(driver, Duration.ofSeconds(15));
    }

    @AfterEach
    public void tearDown() {
        if (driver != null) driver.quit();
    }

    @Test
    @DisplayName("PS5 Recorded Checkout Flow")
    public void testBestbuyPs5Checkout() {
        // Step 1: Navigate to Best Buy
        driver.get("https://www.bestbuy.com");

        // Step 2: Wait for page to load
        wait.until(ExpectedConditions.titleContains("Best Buy"));

        // Step 3: Dismiss popup if present
        try {
            wait.until(ExpectedConditions.elementToBeClickable(
                By.cssSelector("button[aria-label='Close']")
            )).click();
        } catch (Exception ignored) {}

        // Step 4: Click search box
        WebElement searchInput = wait.until(ExpectedConditions.elementToBeClickable(
            By.cssSelector("input#gh-search-input")
        ));
        searchInput.click();

        // Step 5: Type search query and submit
        searchInput.clear();
        searchInput.sendKeys("ps5 console");
        searchInput.sendKeys(Keys.ENTER);

        // Step 6: Wait for search results
        wait.until(ExpectedConditions.presenceOfElementLocated(
            By.cssSelector(".sku-item")
        ));

        // Step 7: Click a PS5 console listing
        wait.until(ExpectedConditions.elementToBeClickable(
            By.xpath("//a[contains(text(),'PlayStation 5') and contains(text(),'Console')]")
        )).click();

        // Step 8: Wait for Add to Cart button
        wait.until(ExpectedConditions.presenceOfElementLocated(
            By.cssSelector("button[data-button-state='ADD_TO_CART']")
        ));

        // Step 9: Add to Cart
        wait.until(ExpectedConditions.elementToBeClickable(
            By.cssSelector("button[data-button-state='ADD_TO_CART']")
        )).click();

        // Step 10: Wait for Go to Cart button
        wait.until(ExpectedConditions.presenceOfElementLocated(
            By.cssSelector(".go-to-cart-button")
        ));

        // Step 11: Go to Cart
        wait.until(ExpectedConditions.elementToBeClickable(
            By.cssSelector(".go-to-cart-button")
        )).click();

        // Step 12: Wait for cart items to load
        wait.until(ExpectedConditions.presenceOfElementLocated(
            By.cssSelector(".cart-item")
        ));

        // Step 13: Click Checkout
        wait.until(ExpectedConditions.elementToBeClickable(
            By.cssSelector("button[data-testid='checkout-button']")
        )).click();

        // Step 14: Wait for Guest Checkout option
        wait.until(ExpectedConditions.presenceOfElementLocated(
            By.cssSelector("button[data-testid='guest-checkout']")
        ));

        // Step 15: Click Guest Checkout
        wait.until(ExpectedConditions.elementToBeClickable(
            By.cssSelector("button[data-testid='guest-checkout']")
        )).click();

        // Step 16: Verify we reached checkout page
        wait.until(driver -> driver.getCurrentUrl().toLowerCase().contains("checkout"));

        // Step 17: Assert checkout URL
        String currentUrl = driver.getCurrentUrl();
        assertTrue(
            currentUrl.toLowerCase().contains("checkout"),
            "Expected checkout page, got: " + currentUrl
        );

        System.out.println("TEST COMPLETE — Reached checkout: " + currentUrl);
    }
}