package com.example.tests;

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.interactions.Actions;
import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

import java.time.Duration;
import java.util.List;

/**
 * Best Buy PS5 Guest Checkout Test
 * ─────────────────────────────────
 * Navigates to bestbuy.com as a guest, searches for a PS5 console,
 * adds it to cart, and proceeds to checkout — stopping BEFORE
 * submitting any payment or placing an order.
 *
 * Prerequisites:
 *   - Chrome browser installed
 *   - JDK 17+
 *   - Network access to bestbuy.com
 *
 * Run:  mvn test -Dtest=BestBuyPS5GuestCheckoutTest
 *
 * Generated by selenium-intellij-mcp-server
 */
public class BestBuyPS5GuestCheckoutTest {

    private WebDriver driver;
    private WebDriverWait wait;
    private WebDriverWait longWait;
    private static final String BASE_URL = "https://www.bestbuy.com";
    private static final String SEARCH_TERM = "ps5 console";

    // ───────────────────────────── Setup / Teardown ─────────────────────────────

    @BeforeEach
    public void setUp() {
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--start-maximized");
        options.addArguments("--disable-notifications");
        options.setExperimentalOption("excludeSwitches", new String[]{"enable-automation"});

        driver = new ChromeDriver(options);
        wait = new WebDriverWait(driver, Duration.ofSeconds(15));
        longWait = new WebDriverWait(driver, Duration.ofSeconds(30));
    }

    @AfterEach
    public void tearDown() {
        if (driver != null) {
            driver.quit();
        }
    }

    // ───────────────────────────── Main Test ─────────────────────────────────────

    @Test
    @DisplayName("PS5 Guest Checkout — stop before placing order")
    public void testPS5GuestCheckoutFlow() {
        navigateToHomePage();
        dismissPopups();
        searchForProduct(SEARCH_TERM);
        selectPS5FromResults();
        addToCart();
        goToCart();
        proceedToCheckoutAsGuest();
        verifyCheckoutPageReached();
    }

    // ───────────────────────────── Step Implementations ──────────────────────────

    private void navigateToHomePage() {
        driver.get(BASE_URL);
        wait.until(ExpectedConditions.titleContains("Best Buy"));
        System.out.println("[STEP 1] ✅ Navigated to Best Buy homepage");
    }

    private void dismissPopups() {
        try {
            List<WebElement> closeBtns = driver.findElements(
                By.cssSelector("[data-testid='close-button'], .c-close-icon, button[aria-label='Close']")
            );
            for (WebElement btn : closeBtns) {
                if (btn.isDisplayed()) {
                    btn.click();
                    Thread.sleep(500);
                }
            }
        } catch (Exception ignored) {}

        try {
            WebElement noThanks = driver.findElement(
                By.xpath("//button[contains(text(),'No, thanks') or contains(text(),'No Thanks') or contains(text(),'Close')]")
            );
            if (noThanks.isDisplayed()) {
                noThanks.click();
                Thread.sleep(500);
            }
        } catch (Exception ignored) {}

        System.out.println("[STEP 2] ✅ Dismissed popups (if any)");
    }

    private void searchForProduct(String query) {
        WebElement searchBox = wait.until(ExpectedConditions.elementToBeClickable(
            By.cssSelector("input#gh-search-input, input[aria-label='Search'], input.search-input")
        ));
        searchBox.clear();
        searchBox.sendKeys(query);
        searchBox.sendKeys(Keys.ENTER);

        wait.until(ExpectedConditions.presenceOfElementLocated(
            By.cssSelector(".sku-item, .list-item, [data-testid='sku-item']")
        ));
        System.out.println("[STEP 3] ✅ Searched for: " + query);
    }

    private void selectPS5FromResults() {
        List<WebElement> products = wait.until(ExpectedConditions.presenceOfAllElementsLocatedBy(
            By.cssSelector(".sku-item .sku-title a, .list-item .sku-title a, [data-testid='sku-title'] a")
        ));

        WebElement ps5Link = null;

        for (WebElement product : products) {
            String title = product.getText().toLowerCase();
            if (title.contains("playstation 5") && title.contains("console")
                && !title.contains("controller") && !title.contains("headset")
                && !title.contains("cover") && !title.contains("charging")) {
                ps5Link = product;
                break;
            }
        }

        if (ps5Link == null) {
            for (WebElement product : products) {
                String title = product.getText().toLowerCase();
                if (title.contains("playstation 5") || title.contains("ps5")) {
                    ps5Link = product;
                    break;
                }
            }
        }

        if (ps5Link == null && !products.isEmpty()) {
            ps5Link = products.get(0);
            System.out.println("[WARN] No exact PS5 match — selecting first result");
        }

        assertNotNull(ps5Link, "No PS5 product found in search results");
        System.out.println("[STEP 4] ✅ Selected product: " + ps5Link.getText());

        ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView({block:'center'});", ps5Link);
        try { Thread.sleep(500); } catch (InterruptedException ignored) {}
        ps5Link.click();

        wait.until(ExpectedConditions.presenceOfElementLocated(
            By.cssSelector(".sku-title h1, .shop-product-title h1, [data-testid='product-title']")
        ));
    }

    private void addToCart() {
        WebElement addToCartBtn = longWait.until(ExpectedConditions.elementToBeClickable(
            By.cssSelector(
                "button[data-button-state='ADD_TO_CART'], " +
                "button.add-to-cart-button:not([disabled]), " +
                "button[data-testid='add-to-cart-button']"
            )
        ));

        ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView({block:'center'});", addToCartBtn);
        try { Thread.sleep(500); } catch (InterruptedException ignored) {}

        addToCartBtn.click();
        System.out.println("[STEP 5] ✅ Clicked Add to Cart");

        try {
            longWait.until(ExpectedConditions.or(
                ExpectedConditions.visibilityOfElementLocated(
                    By.cssSelector(".added-to-cart-modal, [data-testid='added-to-cart'], .go-to-cart-button")
                ),
                ExpectedConditions.textToBePresentInElementLocated(
                    By.cssSelector(".cart-count, [data-testid='cart-count']"), "1"
                )
            ));
        } catch (TimeoutException e) {
            System.out.println("[INFO] No Add-to-Cart modal detected, continuing...");
        }
    }

    private void goToCart() {
        try {
            WebElement goToCart = wait.until(ExpectedConditions.elementToBeClickable(
                By.cssSelector(
                    ".go-to-cart-button, " +
                    "a[data-testid='go-to-cart'], " +
                    "button[data-testid='go-to-cart-button']"
                )
            ));
            goToCart.click();
        } catch (TimeoutException e) {
            driver.get(BASE_URL + "/cart");
        }

        wait.until(ExpectedConditions.presenceOfElementLocated(
            By.cssSelector(".cart-item, [data-testid='cart-item'], .cart-summary")
        ));

        System.out.println("[STEP 6] ✅ Viewing cart page");
    }

    private void proceedToCheckoutAsGuest() {
        WebElement checkoutBtn = wait.until(ExpectedConditions.elementToBeClickable(
            By.cssSelector(
                "button[data-testid='checkout-button'], " +
                "button.checkout-buttons__checkout, " +
                ".cart-summary button.btn-primary, " +
                "a[href*='checkout']"
            )
        ));
        checkoutBtn.click();
        System.out.println("[STEP 7a] ✅ Clicked Checkout button");

        try {
            WebElement guestBtn = longWait.until(ExpectedConditions.elementToBeClickable(
                By.cssSelector(
                    "button[data-testid='guest-checkout'], " +
                    "a[data-testid='guest-checkout'], " +
                    "button.guest-button, " +
                    "a[href*='guest']"
                )
            ));
            guestBtn.click();
            System.out.println("[STEP 7b] ✅ Selected 'Continue as Guest'");
        } catch (TimeoutException e) {
            try {
                WebElement guestLink = driver.findElement(
                    By.xpath(
                        "//button[contains(text(),'Continue as Guest')] | " +
                        "//a[contains(text(),'Continue as Guest')] | " +
                        "//button[contains(text(),'Guest Checkout')] | " +
                        "//a[contains(text(),'Guest')]"
                    )
                );
                guestLink.click();
                System.out.println("[STEP 7b] ✅ Selected guest checkout (xpath fallback)");
            } catch (NoSuchElementException ex) {
                System.out.println("[STEP 7b] No guest prompt — went directly to checkout");
            }
        }
    }

    private void verifyCheckoutPageReached() {
        longWait.until(driver -> {
            String url = driver.getCurrentUrl().toLowerCase();
            return url.contains("checkout") || url.contains("order");
        });

        String currentUrl = driver.getCurrentUrl();
        assertTrue(
            currentUrl.toLowerCase().contains("checkout") ||
            currentUrl.toLowerCase().contains("order"),
            "Expected checkout page, but URL was: " + currentUrl
        );

        System.out.println("[STEP 8] ✅ Reached checkout page: " + currentUrl);
        System.out.println("═══════════════════════════════════════════════");
        System.out.println("  TEST COMPLETE — Stopped BEFORE placing order");
        System.out.println("═══════════════════════════════════════════════");

        takeScreenshot("checkout_reached");
    }

    // ───────────────────────────── Utilities ─────────────────────────────────────

    private void takeScreenshot(String name) {
        try {
            TakesScreenshot ts = (TakesScreenshot) driver;
            byte[] screenshot = ts.getScreenshotAs(OutputType.BYTES);
            java.nio.file.Files.write(
                java.nio.file.Paths.get(System.getProperty("user.dir"), name + ".png"),
                screenshot
            );
            System.out.println("[SCREENSHOT] Saved: " + name + ".png");
        } catch (Exception e) {
            System.out.println("[SCREENSHOT] Failed: " + e.getMessage());
        }
    }
}