/**
 * Page Object Model (POM) generation service.
 * Generates Java POM classes following Selenium best practices.
 */

import { writeFile, mkdir, readFile, readdir } from "node:fs/promises";
import { join, resolve, dirname } from "node:path";
import type { PageObjectConfig, PageElement, PageMethod } from "../types.js";
import type { TestFramework } from "../constants.js";

// ─── POM Class Generation ─────────────────────────────────────────

export function generatePageObjectClass(config: PageObjectConfig): string {
  const { className, packageName, baseUrl, pageTitle, elements, methods } = config;

  const imports = [
    "org.openqa.selenium.WebDriver",
    "org.openqa.selenium.WebElement",
    "org.openqa.selenium.By",
    "org.openqa.selenium.support.FindBy",
    "org.openqa.selenium.support.PageFactory",
    "org.openqa.selenium.support.ui.WebDriverWait",
    "org.openqa.selenium.support.ui.ExpectedConditions",
    "java.time.Duration"
  ];

  const lines: string[] = [];

  // Package declaration
  lines.push(`package ${packageName};`);
  lines.push("");

  // Imports
  for (const imp of imports) {
    lines.push(`import ${imp};`);
  }
  lines.push("");

  // Class javadoc
  lines.push("/**");
  lines.push(` * Page Object for ${className.replace(/Page$/, "")} page.`);
  if (baseUrl) lines.push(` * URL: ${baseUrl}`);
  if (pageTitle) lines.push(` * Title: ${pageTitle}`);
  lines.push(" *");
  lines.push(" * Generated by selenium-intellij-mcp-server");
  lines.push(" */");

  // Class declaration
  lines.push(`public class ${className} {`);
  lines.push("");
  lines.push("    private final WebDriver driver;");
  lines.push("    private final WebDriverWait wait;");
  if (baseUrl) {
    lines.push(`    private static final String BASE_URL = "${baseUrl}";`);
  }
  lines.push("");

  // Element declarations with @FindBy
  for (const el of elements) {
    lines.push(`    /** ${el.description ?? el.name} */`);
    lines.push(`    @FindBy(${mapFindByStrategy(el.locatorStrategy, el.locatorValue)})`);
    lines.push(`    private WebElement ${el.name};`);
    lines.push("");
  }

  // Constructor
  lines.push("    /**");
  lines.push(`     * Initialize ${className} with WebDriver.`);
  lines.push("     * @param driver WebDriver instance");
  lines.push("     */");
  lines.push(`    public ${className}(WebDriver driver) {`);
  lines.push("        this.driver = driver;");
  lines.push("        this.wait = new WebDriverWait(driver, Duration.ofSeconds(10));");
  lines.push("        PageFactory.initElements(driver, this);");
  lines.push("    }");
  lines.push("");

  // Navigate method (if baseUrl provided)
  if (baseUrl) {
    lines.push("    /**");
    lines.push("     * Navigate to this page.");
    lines.push(`     * @return this ${className} instance`);
    lines.push("     */");
    lines.push(`    public ${className} navigateTo() {`);
    lines.push("        driver.get(BASE_URL);");
    lines.push(`        return this;`);
    lines.push("    }");
    lines.push("");
  }

  // isLoaded check
  if (pageTitle) {
    lines.push("    /**");
    lines.push("     * Verify the page is loaded.");
    lines.push("     * @return true if page title matches");
    lines.push("     */");
    lines.push("    public boolean isLoaded() {");
    lines.push(`        return driver.getTitle().contains("${pageTitle}");`);
    lines.push("    }");
    lines.push("");
  }

  // Auto-generated element interaction methods
  for (const el of elements) {
    generateElementMethods(lines, el, className);
  }

  // Custom methods
  if (methods) {
    for (const method of methods) {
      lines.push("    /**");
      lines.push(`     * ${method.description}`);
      lines.push(`     * @return ${method.returnType}`);
      lines.push("     */");
      lines.push(`    public ${method.returnType} ${method.name}() {`);
      for (const step of method.steps) {
        lines.push(`        ${step}`);
      }
      lines.push("    }");
      lines.push("");
    }
  }

  lines.push("}");

  return lines.join("\n");
}

function mapFindByStrategy(strategy: string, value: string): string {
  switch (strategy) {
    case "id": return `id = "${value}"`;
    case "name": return `name = "${value}"`;
    case "className": return `className = "${value}"`;
    case "tagName": return `tagName = "${value}"`;
    case "css": return `css = "${value}"`;
    case "xpath": return `xpath = "${value}"`;
    case "linkText": return `linkText = "${value}"`;
    case "partialLinkText": return `partialLinkText = "${value}"`;
    default: return `css = "${value}"`;
  }
}

function generateElementMethods(lines: string[], el: PageElement, className: string): void {
  const capName = el.name.charAt(0).toUpperCase() + el.name.slice(1);

  switch (el.type) {
    case "button":
    case "link":
      lines.push(`    /** Click the ${el.name} element. */`);
      lines.push(`    public ${className} click${capName}() {`);
      lines.push(`        wait.until(ExpectedConditions.elementToBeClickable(${el.name}));`);
      lines.push(`        ${el.name}.click();`);
      lines.push(`        return this;`);
      lines.push("    }");
      lines.push("");
      break;

    case "input":
      lines.push(`    /** Type text into the ${el.name} field. */`);
      lines.push(`    public ${className} enter${capName}(String text) {`);
      lines.push(`        wait.until(ExpectedConditions.visibilityOf(${el.name}));`);
      lines.push(`        ${el.name}.clear();`);
      lines.push(`        ${el.name}.sendKeys(text);`);
      lines.push(`        return this;`);
      lines.push("    }");
      lines.push("");
      lines.push(`    /** Get the value of the ${el.name} field. */`);
      lines.push(`    public String get${capName}Value() {`);
      lines.push(`        return ${el.name}.getAttribute("value");`);
      lines.push("    }");
      lines.push("");
      break;

    case "text":
      lines.push(`    /** Get the text of the ${el.name} element. */`);
      lines.push(`    public String get${capName}Text() {`);
      lines.push(`        wait.until(ExpectedConditions.visibilityOf(${el.name}));`);
      lines.push(`        return ${el.name}.getText();`);
      lines.push("    }");
      lines.push("");
      break;

    case "select":
      lines.push(`    /** Select an option by visible text in ${el.name}. */`);
      lines.push(`    public ${className} select${capName}ByText(String text) {`);
      lines.push(`        new org.openqa.selenium.support.ui.Select(${el.name}).selectByVisibleText(text);`);
      lines.push(`        return this;`);
      lines.push("    }");
      lines.push("");
      lines.push(`    /** Select an option by value in ${el.name}. */`);
      lines.push(`    public ${className} select${capName}ByValue(String value) {`);
      lines.push(`        new org.openqa.selenium.support.ui.Select(${el.name}).selectByValue(value);`);
      lines.push(`        return this;`);
      lines.push("    }");
      lines.push("");
      break;

    case "checkbox":
    case "radio":
      lines.push(`    /** Check/select the ${el.name} element. */`);
      lines.push(`    public ${className} select${capName}() {`);
      lines.push(`        if (!${el.name}.isSelected()) {`);
      lines.push(`            ${el.name}.click();`);
      lines.push(`        }`);
      lines.push(`        return this;`);
      lines.push("    }");
      lines.push("");
      if (el.type === "checkbox") {
        lines.push(`    /** Uncheck the ${el.name} element. */`);
        lines.push(`    public ${className} deselect${capName}() {`);
        lines.push(`        if (${el.name}.isSelected()) {`);
        lines.push(`            ${el.name}.click();`);
        lines.push(`        }`);
        lines.push(`        return this;`);
        lines.push("    }");
        lines.push("");
      }
      lines.push(`    /** Check if ${el.name} is selected. */`);
      lines.push(`    public boolean is${capName}Selected() {`);
      lines.push(`        return ${el.name}.isSelected();`);
      lines.push("    }");
      lines.push("");
      break;

    default:
      lines.push(`    /** Get the ${el.name} WebElement. */`);
      lines.push(`    public WebElement get${capName}() {`);
      lines.push(`        return ${el.name};`);
      lines.push("    }");
      lines.push("");
  }

  // isDisplayed for all elements
  lines.push(`    /** Check if ${el.name} is displayed. */`);
  lines.push(`    public boolean is${capName}Displayed() {`);
  lines.push("        try {");
  lines.push(`            return ${el.name}.isDisplayed();`);
  lines.push("        } catch (org.openqa.selenium.NoSuchElementException e) {");
  lines.push("            return false;");
  lines.push("        }");
  lines.push("    }");
  lines.push("");
}

// ─── Test Class Generation ────────────────────────────────────────

export function generateTestClass(
  pomConfig: PageObjectConfig,
  framework: TestFramework
): string {
  const { className, packageName } = pomConfig;
  const testClassName = `${className}Test`;
  const lines: string[] = [];

  lines.push(`package ${packageName};`);
  lines.push("");

  // Framework-specific imports
  if (framework === "junit5") {
    lines.push("import org.junit.jupiter.api.*;");
    lines.push("import static org.junit.jupiter.api.Assertions.*;");
  } else if (framework === "junit4") {
    lines.push("import org.junit.*;");
    lines.push("import static org.junit.Assert.*;");
  } else {
    lines.push("import org.testng.annotations.*;");
    lines.push("import static org.testng.Assert.*;");
  }
  lines.push("import org.openqa.selenium.WebDriver;");
  lines.push("import org.openqa.selenium.chrome.ChromeDriver;");
  lines.push("import org.openqa.selenium.chrome.ChromeOptions;");
  lines.push("");

  lines.push(`public class ${testClassName} {`);
  lines.push("");
  lines.push("    private WebDriver driver;");
  lines.push(`    private ${className} page;`);
  lines.push("");

  // Setup
  const setupAnnotation = framework === "junit5" ? "@BeforeEach" : framework === "junit4" ? "@Before" : "@BeforeMethod";
  lines.push(`    ${setupAnnotation}`);
  lines.push("    public void setUp() {");
  lines.push("        ChromeOptions options = new ChromeOptions();");
  lines.push('        options.addArguments("--headless=new");');
  lines.push("        driver = new ChromeDriver(options);");
  lines.push(`        page = new ${className}(driver);`);
  lines.push("    }");
  lines.push("");

  // Teardown
  const teardownAnnotation = framework === "junit5" ? "@AfterEach" : framework === "junit4" ? "@After" : "@AfterMethod";
  lines.push(`    ${teardownAnnotation}`);
  lines.push("    public void tearDown() {");
  lines.push("        if (driver != null) {");
  lines.push("            driver.quit();");
  lines.push("        }");
  lines.push("    }");
  lines.push("");

  // Sample test: page loads
  if (pomConfig.baseUrl) {
    const testAnnotation = framework === "testng" ? "@Test" : "@Test";
    lines.push(`    ${testAnnotation}`);
    lines.push("    public void testPageLoads() {");
    lines.push("        page.navigateTo();");
    if (pomConfig.pageTitle) {
      lines.push(`        assertTrue(page.isLoaded(), "Page should be loaded");`);
    }
    lines.push("    }");
    lines.push("");
  }

  // Sample test for each element
  for (const el of pomConfig.elements.slice(0, 5)) {
    const capName = el.name.charAt(0).toUpperCase() + el.name.slice(1);
    const testAnnotation = "@Test";

    lines.push(`    ${testAnnotation}`);
    lines.push(`    public void test${capName}IsDisplayed() {`);
    if (pomConfig.baseUrl) lines.push("        page.navigateTo();");
    lines.push(`        assertTrue(page.is${capName}Displayed(), "${el.name} should be displayed");`);
    lines.push("    }");
    lines.push("");
  }

  lines.push("}");
  return lines.join("\n");
}

// ─── File Operations ──────────────────────────────────────────────

export async function writePomToFile(
  projectPath: string,
  config: PageObjectConfig,
  content: string
): Promise<string> {
  const packagePath = config.packageName.replace(/\./g, "/");
  const filePath = join(resolve(projectPath), "src", "main", "java", packagePath, `${config.className}.java`);
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, content, "utf-8");
  return filePath;
}

export async function writeTestToFile(
  projectPath: string,
  config: PageObjectConfig,
  content: string
): Promise<string> {
  const packagePath = config.packageName.replace(/\./g, "/");
  const filePath = join(resolve(projectPath), "src", "test", "java", packagePath, `${config.className}Test.java`);
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, content, "utf-8");
  return filePath;
}

// ─── POM from Live Page (Auto-Discovery) ──────────────────────────

export function generatePomFromElements(
  className: string,
  packageName: string,
  pageUrl: string,
  pageTitle: string,
  discoveredElements: Array<{
    tag: string;
    id?: string;
    name?: string;
    className?: string;
    type?: string;
    text?: string;
    xpath?: string;
  }>
): PageObjectConfig {
  const elements: PageElement[] = [];

  for (const el of discoveredElements) {
    let locatorStrategy: PageElement["locatorStrategy"] = "css";
    let locatorValue = el.xpath ?? "";
    let elType: PageElement["type"] = "custom";

    // Determine best locator strategy
    if (el.id) {
      locatorStrategy = "id";
      locatorValue = el.id;
    } else if (el.name) {
      locatorStrategy = "name";
      locatorValue = el.name;
    } else if (el.className) {
      locatorStrategy = "css";
      locatorValue = `.${el.className.split(" ").join(".")}`;              }

    // Determine element type
    const tag = el.tag.toLowerCase();
    if (tag === "button" || (tag === "input" && el.type === "submit")) {
      elType = "button";
    } else if (tag === "a") {
      elType = "link";
    } else if (tag === "input") {
      if (el.type === "checkbox") elType = "checkbox";
      else if (el.type === "radio") elType = "radio";
      else elType = "input";
    } else if (tag === "select") {
      elType = "select";
    } else if (["span", "p", "h1", "h2", "h3", "h4", "h5", "h6", "div", "label"].includes(tag)) {
      elType = "text";
    }

    // Generate a meaningful name
    const elName = generateFieldName(el.id ?? el.name ?? el.text ?? el.tag, elType);

    elements.push({
      name: elName,
      locatorStrategy,
      locatorValue,
      description: el.text ? `${el.tag}: ${el.text.slice(0, 60)}` : el.tag,
      type: elType
    });
  }

  return {
    className,
    packageName,
    baseUrl: pageUrl,
    pageTitle,
    elements
  };
}

function generateFieldName(hint: string, type: string): string {
  // Clean and camelCase the hint
  let name = hint
    .replace(/[^a-zA-Z0-9\s]/g, "")
    .trim()
    .split(/\s+/)
    .map((w, i) => i === 0 ? w.toLowerCase() : w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join("")
    .slice(0, 30);

  if (!name || /^\d/.test(name)) name = type + name;

  // Add suffix if not already descriptive
  const typeSuffixes: Record<string, string> = {
    button: "Button", link: "Link", input: "Input",
    select: "Select", checkbox: "Checkbox", radio: "Radio"
  };
  if (typeSuffixes[type] && !name.toLowerCase().endsWith(type)) {
    name += typeSuffixes[type];
  }

  return name;
}