/**
 * Selenium IDE-style recording service.
 * Records browser actions and exports them as Java test code
 * (JUnit 4/5 or TestNG) or as a Selenium IDE .side JSON file.
 */

import type { RecordedAction, RecordedTest } from "../types.js";
import type { TestFramework } from "../constants.js";

// ─── In-Memory Store ─────────────────────────────────────────────

const recordings = new Map<string, RecordedTest>();

// ─── Recording Lifecycle ─────────────────────────────────────────

export function startRecording(name: string, baseUrl: string): RecordedTest {
  const test: RecordedTest = {
    name,
    baseUrl,
    actions: [],
    createdAt: new Date().toISOString()
  };
  recordings.set(name, test);
  return test;
}

export function stopRecording(name: string): RecordedTest | null {
  return recordings.get(name) ?? null;
}

export function deleteRecording(name: string): boolean {
  return recordings.delete(name);
}

export function listRecordings(): RecordedTest[] {
  return [...recordings.values()];
}

export function getRecording(name: string): RecordedTest | null {
  return recordings.get(name) ?? null;
}

// ─── Action Recording ────────────────────────────────────────────

export function addAction(name: string, action: Omit<RecordedAction, "timestamp">): RecordedAction | null {
  const recording = recordings.get(name);
  if (!recording) return null;

  const fullAction: RecordedAction = {
    ...action,
    timestamp: Date.now()
  };
  recording.actions.push(fullAction);
  return fullAction;
}

// ─── Export to Java Test Code ────────────────────────────────────

export function exportToJava(
  name: string,
  options: {
    packageName: string;
    framework: TestFramework;
    className?: string;
  }
): string | null {
  const recording = recordings.get(name);
  if (!recording) return null;

  const { packageName, framework, className } = options;
  const testClassName = className ?? toPascalCase(recording.name) + "Test";
  const lines: string[] = [];

  // Package
  lines.push(`package ${packageName};`);
  lines.push("");

  // Imports
  lines.push("import org.openqa.selenium.WebDriver;");
  lines.push("import org.openqa.selenium.WebElement;");
  lines.push("import org.openqa.selenium.By;");
  lines.push("import org.openqa.selenium.chrome.ChromeDriver;");
  lines.push("import org.openqa.selenium.chrome.ChromeOptions;");
  lines.push("import org.openqa.selenium.support.ui.WebDriverWait;");
  lines.push("import org.openqa.selenium.support.ui.ExpectedConditions;");
  lines.push("import org.openqa.selenium.support.ui.Select;");
  lines.push("import org.openqa.selenium.Keys;");
  lines.push("import org.openqa.selenium.interactions.Actions;");
  lines.push("import java.time.Duration;");

  if (framework === "junit5") {
    lines.push("import org.junit.jupiter.api.*;");
    lines.push("import static org.junit.jupiter.api.Assertions.*;");
  } else if (framework === "junit4") {
    lines.push("import org.junit.*;");
    lines.push("import static org.junit.Assert.*;");
  } else {
    lines.push("import org.testng.annotations.*;");
    lines.push("import static org.testng.Assert.*;");
  }
  lines.push("");

  // Class
  lines.push("/**");
  lines.push(` * Recorded test: ${recording.name}`);
  lines.push(` * Base URL: ${recording.baseUrl}`);
  lines.push(` * Recorded at: ${recording.createdAt}`);
  lines.push(` * Actions: ${recording.actions.length}`);
  lines.push(" *");
  lines.push(" * Generated by selenium-intellij-mcp-server recording service");
  lines.push(" */");
  lines.push(`public class ${testClassName} {`);
  lines.push("");
  lines.push("    private WebDriver driver;");
  lines.push("    private WebDriverWait wait;");
  lines.push("");

  // Setup
  const setupAnn = framework === "junit5" ? "@BeforeEach" : framework === "junit4" ? "@Before" : "@BeforeMethod";
  lines.push(`    ${setupAnn}`);
  lines.push("    public void setUp() {");
  lines.push("        ChromeOptions options = new ChromeOptions();");
  lines.push("        driver = new ChromeDriver(options);");
  lines.push("        wait = new WebDriverWait(driver, Duration.ofSeconds(10));");
  lines.push(`        driver.get("${escapeJava(recording.baseUrl)}");`);
  lines.push("    }");
  lines.push("");

  // Teardown
  const tearAnn = framework === "junit5" ? "@AfterEach" : framework === "junit4" ? "@After" : "@AfterMethod";
  lines.push(`    ${tearAnn}`);
  lines.push("    public void tearDown() {");
  lines.push("        if (driver != null) driver.quit();");
  lines.push("    }");
  lines.push("");

  // Test method
  lines.push("    @Test");
  lines.push(`    public void test${toPascalCase(recording.name)}() {`);

  for (const action of recording.actions) {
    const javaLine = actionToJava(action);
    if (javaLine) lines.push(`        ${javaLine}`);
  }

  lines.push("    }");
  lines.push("}");

  return lines.join("\n");
}

// ─── Export to Selenium IDE .side Format ─────────────────────────

export function exportToSide(name: string): object | null {
  const recording = recordings.get(name);
  if (!recording) return null;

  const testId = crypto.randomUUID?.() ?? `test-${Date.now()}`;
  const suiteId = crypto.randomUUID?.() ?? `suite-${Date.now()}`;
  const projectId = crypto.randomUUID?.() ?? `project-${Date.now()}`;

  const commands = recording.actions.map((action, i) => ({
    id: `cmd-${i}`,
    command: action.command,
    target: action.target,
    targets: [[action.target, action.command]],
    value: action.value,
    comment: ""
  }));

  return {
    id: projectId,
    version: "2.0",
    name: recording.name,
    url: recording.baseUrl,
    tests: [{
      id: testId,
      name: recording.name,
      commands
    }],
    suites: [{
      id: suiteId,
      name: "Default Suite",
      persistSession: false,
      parallel: false,
      timeout: 300,
      tests: [testId]
    }],
    urls: [recording.baseUrl],
    plugins: []
  };
}

// ─── Helpers ─────────────────────────────────────────────────────

function actionToJava(action: RecordedAction): string {
  const { command, target, value } = action;

  switch (command) {
    case "open":
      return `driver.get("${escapeJava(target)}");`;
    case "click":
      return `wait.until(ExpectedConditions.elementToBeClickable(${byLocator(target)})).click();`;
    case "doubleClick":
      return `new Actions(driver).doubleClick(wait.until(ExpectedConditions.elementToBeClickable(${byLocator(target)}))).perform();`;
    case "type":
    case "sendKeys":
      return `{ WebElement el = wait.until(ExpectedConditions.visibilityOfElementLocated(${byLocator(target)})); el.clear(); el.sendKeys("${escapeJava(value)}"); }`;
    case "select":
      return `new Select(driver.findElement(${byLocator(target)})).selectByVisibleText("${escapeJava(value)}");`;
    case "check":
      return `{ WebElement cb = driver.findElement(${byLocator(target)}); if (!cb.isSelected()) cb.click(); }`;
    case "uncheck":
      return `{ WebElement cb = driver.findElement(${byLocator(target)}); if (cb.isSelected()) cb.click(); }`;
    case "assertText":
      return `assertEquals("${escapeJava(value)}", driver.findElement(${byLocator(target)}).getText());`;
    case "assertElementPresent":
      return `assertTrue(driver.findElements(${byLocator(target)}).size() > 0);`;
    case "assertTitle":
      return `assertEquals("${escapeJava(value)}", driver.getTitle());`;
    case "waitForElementPresent":
      return `wait.until(ExpectedConditions.presenceOfElementLocated(${byLocator(target)}));`;
    case "waitForElementVisible":
      return `wait.until(ExpectedConditions.visibilityOfElementLocated(${byLocator(target)}));`;
    case "pause":
      return `Thread.sleep(${parseInt(value) || 1000});`;
    case "mouseOver":
      return `new Actions(driver).moveToElement(driver.findElement(${byLocator(target)})).perform();`;
    case "dragAndDrop":
      return `new Actions(driver).dragAndDrop(driver.findElement(${byLocator(target)}), driver.findElement(${byLocator(value)})).perform();`;
    case "executeScript":
      return `((org.openqa.selenium.JavascriptExecutor) driver).executeScript("${escapeJava(target)}");`;
    case "setWindowSize":
      return `driver.manage().window().setSize(new org.openqa.selenium.Dimension(${target}));`;
    default:
      return `// TODO: Unrecognized command '${command}' target='${target}' value='${value}'`;
  }
}

function byLocator(target: string): string {
  if (target.startsWith("id=")) return `By.id("${escapeJava(target.slice(3))}")` ;
  if (target.startsWith("name=")) return `By.name("${escapeJava(target.slice(5))}")` ;
  if (target.startsWith("css=")) return `By.cssSelector("${escapeJava(target.slice(4))}")` ;
  if (target.startsWith("xpath=")) return `By.xpath("${escapeJava(target.slice(6))}")` ;
  if (target.startsWith("linkText=")) return `By.linkText("${escapeJava(target.slice(9))}")` ;
  if (target.startsWith("partialLinkText=")) return `By.partialLinkText("${escapeJava(target.slice(16))}")` ;
  if (target.startsWith("//") || target.startsWith("(//")) return `By.xpath("${escapeJava(target)}")` ;
  // Default to CSS
  return `By.cssSelector("${escapeJava(target)}")` ;
}

function escapeJava(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n").replace(/\r/g, "\\r");
}

function toPascalCase(s: string): string {
  return s
    .replace(/[^a-zA-Z0-9\s_-]/g, "")
    .split(/[\s_-]+/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join("");
}