package com.example.tests;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.By;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.Keys;
import org.openqa.selenium.interactions.Actions;
import java.time.Duration;
import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Recorded test: bestbuy-ps5-checkout
 * Base URL: https://www.bestbuy.com
 * Actions: 18
 *
 * Generated by selenium-intellij-mcp-server recording service
 */
public class BestBuyPS5RecordedTest {

    private WebDriver driver;
    private WebDriverWait wait;

    @BeforeEach
    public void setUp() {
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--start-maximized");
        driver = new ChromeDriver(options);
        wait = new WebDriverWait(driver, Duration.ofSeconds(15));
        driver.get("https://www.bestbuy.com");
    }

    @AfterEach
    public void tearDown() {
        if (driver != null) driver.quit();
    }

    @Test
    @DisplayName("Best Buy PS5 Guest Checkout — MCP Recorded")
    public void testBestbuyPs5Checkout() {
        // Step 1: Open Best Buy
        driver.get("https://www.bestbuy.com");

        // Step 2: Wait for page load
        wait.until(ExpectedConditions.titleContains("Best Buy"));

        // Step 3: Dismiss popup
        try {
            wait.until(ExpectedConditions.elementToBeClickable(
                By.cssSelector("button[aria-label='Close']")
            )).click();
        } catch (Exception ignored) {}

        // Step 4-6: Search for PS5
        WebElement searchBox = wait.until(ExpectedConditions.elementToBeClickable(
            By.cssSelector("input#gh-search-input")
        ));
        searchBox.click();
        searchBox.clear();
        searchBox.sendKeys("ps5 console");
        searchBox.sendKeys(Keys.ENTER);

        // Step 7: Wait for results
        wait.until(ExpectedConditions.presenceOfElementLocated(
            By.cssSelector(".sku-item")
        ));

        // Step 8: Click PS5 console listing
        wait.until(ExpectedConditions.elementToBeClickable(
            By.xpath("//a[contains(text(),'PlayStation 5') and contains(text(),'Console')]")
        )).click();

        // Step 9-10: Add to Cart
        wait.until(ExpectedConditions.presenceOfElementLocated(
            By.cssSelector("button[data-button-state='ADD_TO_CART']")
        ));
        wait.until(ExpectedConditions.elementToBeClickable(
            By.cssSelector("button[data-button-state='ADD_TO_CART']")
        )).click();

        // Step 11-12: Go to Cart
        wait.until(ExpectedConditions.presenceOfElementLocated(
            By.cssSelector(".go-to-cart-button")
        ));
        wait.until(ExpectedConditions.elementToBeClickable(
            By.cssSelector(".go-to-cart-button")
        )).click();

        // Step 13-14: Proceed to Checkout
        wait.until(ExpectedConditions.presenceOfElementLocated(
            By.cssSelector(".cart-item")
        ));
        wait.until(ExpectedConditions.elementToBeClickable(
            By.cssSelector("button[data-testid='checkout-button']")
        )).click();

        // Step 15-16: Continue as Guest
        wait.until(ExpectedConditions.presenceOfElementLocated(
            By.cssSelector("button[data-testid='guest-checkout']")
        ));
        wait.until(ExpectedConditions.elementToBeClickable(
            By.cssSelector("button[data-testid='guest-checkout']")
        )).click();

        // Step 17-18: Verify checkout page reached — STOP HERE
        wait.until(driver -> driver.getCurrentUrl().toLowerCase().contains("checkout"));
        assertTrue(driver.getCurrentUrl().toLowerCase().contains("checkout"),
            "Should be on checkout page");

        System.out.println("TEST COMPLETE — Reached checkout, stopped before placing order.");
    }
}