package com.example.tests;

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.interactions.Actions;
import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

import java.time.Duration;
import java.util.List;

/**
 * Best Buy PS5 Guest Checkout Test
 * ─────────────────────────────────
 * Navigates to bestbuy.com as a guest, searches for a PS5 console,
 * adds it to cart, and proceeds to checkout — stopping BEFORE
 * submitting any payment or placing an order.
 *
 * Prerequisites:
 *   - ChromeDriver on PATH (or use WebDriverManager)
 *   - Chrome browser installed
 *   - Network access to bestbuy.com
 *
 * Run:  mvn test -Dtest=BestBuyPS5GuestCheckoutTest
 *
 * Generated by selenium-intellij-mcp-server
 */
public class BestBuyPS5GuestCheckoutTest {

    private WebDriver driver;
    private WebDriverWait wait;
    private WebDriverWait longWait;
    private static final String BASE_URL = "https://www.bestbuy.com";
    private static final String SEARCH_TERM = "ps5 console";

    // ───────────────────────────── Setup / Teardown ─────────────────────────────

    @BeforeEach
    public void setUp() {
        ChromeOptions options = new ChromeOptions();
        // Maximize window so all elements are visible
        options.addArguments("--start-maximized");
        // Disable notifications popup
        options.addArguments("--disable-notifications");
        // Disable "Chrome is being controlled by automated software" bar
        options.setExperimentalOption("excludeSwitches", new String[]{"enable-automation"});

        driver = new ChromeDriver(options);
        wait = new WebDriverWait(driver, Duration.ofSeconds(15));
        longWait = new WebDriverWait(driver, Duration.ofSeconds(30));
    }

    @AfterEach
    public void tearDown() {
        if (driver != null) {
            driver.quit();
        }
    }

    // ───────────────────────────── Main Test ─────────────────────────────────────

    @Test
    @DisplayName("PS5 Guest Checkout — stop before placing order")
    public void testPS5GuestCheckoutFlow() {
        // Step 1: Navigate to Best Buy
        navigateToHomePage();

        // Step 2: Dismiss any popups / cookie banners
        dismissPopups();

        // Step 3: Search for PS5
        searchForProduct(SEARCH_TERM);

        // Step 4: Select a PS5 console from results
        selectPS5FromResults();

        // Step 5: Add to Cart
        addToCart();

        // Step 6: Go to Cart
        goToCart();

        // Step 7: Proceed to Checkout as Guest
        proceedToCheckoutAsGuest();

        // Step 8: Verify we reached the checkout page — STOP here
        verifyCheckoutPageReached();
    }

    // ───────────────────────────── Step Implementations ──────────────────────────

    private void navigateToHomePage() {
        driver.get(BASE_URL);
        wait.until(ExpectedConditions.titleContains("Best Buy"));
        System.out.println("[STEP 1] ✅ Navigated to Best Buy homepage");
    }

    private void dismissPopups() {
        // Best Buy may show a location/cookie modal or promotional overlay
        try {
            // Close cookie/privacy banner if present
            List<WebElement> closeBtns = driver.findElements(
                By.cssSelector("[data-testid='close-button'], .c-close-icon, button[aria-label='Close']")
            );
            for (WebElement btn : closeBtns) {
                if (btn.isDisplayed()) {
                    btn.click();
                    Thread.sleep(500);
                }
            }
        } catch (Exception ignored) {
            // No popup to dismiss — continue
        }

        // Dismiss "Are you a Best Buy member?" or similar overlays
        try {
            WebElement noThanks = driver.findElement(
                By.xpath("//button[contains(text(),'No, thanks') or contains(text(),'No Thanks') or contains(text(),'Close')]")
            );
            if (noThanks.isDisplayed()) {
                noThanks.click();
                Thread.sleep(500);
            }
        } catch (Exception ignored) {}

        System.out.println("[STEP 2] ✅ Dismissed popups (if any)");
    }

    private void searchForProduct(String query) {
        // Best Buy search bar — multiple selector fallbacks
        WebElement searchBox = wait.until(ExpectedConditions.elementToBeClickable(
            By.cssSelector("input#gh-search-input, input[aria-label='Search'], input.search-input")
        ));
        searchBox.clear();
        searchBox.sendKeys(query);
        searchBox.sendKeys(Keys.ENTER);

        // Wait for search results page to load
        wait.until(ExpectedConditions.presenceOfElementLocated(
            By.cssSelector(".sku-item, .list-item, [data-testid='sku-item']")
        ));
        System.out.println("[STEP 3] ✅ Searched for: " + query);
    }

    private void selectPS5FromResults() {
        // Strategy: find product listings, prefer "PlayStation 5" console (not accessories)
        // Best Buy uses .sku-item containers with .sku-title links
        List<WebElement> products = wait.until(ExpectedConditions.presenceOfAllElementsLocatedBy(
            By.cssSelector(".sku-item .sku-title a, .list-item .sku-title a, [data-testid='sku-title'] a")
        ));

        WebElement ps5Link = null;

        // Prefer exact PS5 console match (not controller, headset, etc.)
        for (WebElement product : products) {
            String title = product.getText().toLowerCase();
            if (title.contains("playstation 5") && title.contains("console")
                && !title.contains("controller") && !title.contains("headset")
                && !title.contains("cover") && !title.contains("charging")) {
                ps5Link = product;
                break;
            }
        }

        // Fallback: first item containing "playstation 5" or "ps5"
        if (ps5Link == null) {
            for (WebElement product : products) {
                String title = product.getText().toLowerCase();
                if (title.contains("playstation 5") || title.contains("ps5")) {
                    ps5Link = product;
                    break;
                }
            }
        }

        // Last resort: click the first product
        if (ps5Link == null && !products.isEmpty()) {
            ps5Link = products.get(0);
            System.out.println("[WARN] No exact PS5 match found — selecting first result");
        }

        assertNotNull(ps5Link, "No PS5 product found in search results");
        System.out.println("[STEP 4] ✅ Selected product: " + ps5Link.getText());

        // Scroll into view and click
        ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView({block:'center'});", ps5Link);
        try { Thread.sleep(500); } catch (InterruptedException ignored) {}
        ps5Link.click();

        // Wait for PDP (Product Detail Page) to load
        wait.until(ExpectedConditions.presenceOfElementLocated(
            By.cssSelector(".sku-title h1, .shop-product-title h1, [data-testid='product-title']")
        ));
    }

    private void addToCart() {
        // Wait for the Add to Cart button to be clickable
        // Best Buy uses data-button-state="ADD_TO_CART" or "Add to Cart" text
        WebElement addToCartBtn = longWait.until(ExpectedConditions.elementToBeClickable(
            By.cssSelector(
                "button[data-button-state='ADD_TO_CART'], " +
                "button.add-to-cart-button:not([disabled]), " +
                "button[data-testid='add-to-cart-button']"
            )
        ));

        // Scroll into view to avoid "element not interactable"
        ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView({block:'center'});", addToCartBtn);
        try { Thread.sleep(500); } catch (InterruptedException ignored) {}

        addToCartBtn.click();
        System.out.println("[STEP 5] ✅ Clicked Add to Cart");

        // Wait for "Added to Cart" confirmation overlay or cart count update
        try {
            longWait.until(ExpectedConditions.or(
                ExpectedConditions.visibilityOfElementLocated(
                    By.cssSelector(".added-to-cart-modal, [data-testid='added-to-cart'], .go-to-cart-button")
                ),
                ExpectedConditions.textToBePresentInElementLocated(
                    By.cssSelector(".cart-count, [data-testid='cart-count']"), "1"
                )
            ));
        } catch (TimeoutException e) {
            // Cart may have updated without a modal — check cart icon
            System.out.println("[INFO] No Add-to-Cart modal detected, continuing to cart...");
        }
    }

    private void goToCart() {
        // Try clicking "Go to Cart" button in the overlay first
        try {
            WebElement goToCart = wait.until(ExpectedConditions.elementToBeClickable(
                By.cssSelector(
                    ".go-to-cart-button, " +
                    "a[data-testid='go-to-cart'], " +
                    "button[data-testid='go-to-cart-button']"
                )
            ));
            goToCart.click();
        } catch (TimeoutException e) {
            // Overlay didn't appear — navigate directly to cart page
            driver.get(BASE_URL + "/cart");
        }

        // Wait for cart page to load with at least one item
        wait.until(ExpectedConditions.presenceOfElementLocated(
            By.cssSelector(
                ".cart-item, " +
                "[data-testid='cart-item'], " +
                ".cart-summary"
            )
        ));

        System.out.println("[STEP 6] ✅ Viewing cart page");
    }

    private void proceedToCheckoutAsGuest() {
        // Click "Checkout" or "Proceed to Checkout" button
        WebElement checkoutBtn = wait.until(ExpectedConditions.elementToBeClickable(
            By.cssSelector(
                "button[data-testid='checkout-button'], " +
                "button.checkout-buttons__checkout, " +
                ".cart-summary button.btn-primary, " +
                "a[href*='checkout']"
            )
        ));
        checkoutBtn.click();
        System.out.println("[STEP 7a] ✅ Clicked Checkout button");

        // Best Buy will prompt for sign-in or guest checkout
        // Wait for the sign-in / guest option page
        try {
            // Look for "Continue as Guest" option
            WebElement guestBtn = longWait.until(ExpectedConditions.elementToBeClickable(
                By.cssSelector(
                    "button[data-testid='guest-checkout'], " +
                    "a[data-testid='guest-checkout'], " +
                    "button.guest-button, " +
                    "a[href*='guest']"
                )
            ));
            guestBtn.click();
            System.out.println("[STEP 7b] ✅ Selected 'Continue as Guest'");
        } catch (TimeoutException e) {
            // Some flows skip the guest/sign-in choice — try xpath fallback
            try {
                WebElement guestLink = driver.findElement(
                    By.xpath(
                        "//button[contains(text(),'Continue as Guest')] | " +
                        "//a[contains(text(),'Continue as Guest')] | " +
                        "//button[contains(text(),'Guest Checkout')] | " +
                        "//a[contains(text(),'Guest')]"
                    )
                );
                guestLink.click();
                System.out.println("[STEP 7b] ✅ Selected guest checkout (xpath fallback)");
            } catch (NoSuchElementException ex) {
                // May have gone directly to checkout — that's fine
                System.out.println("[STEP 7b] ℹ️  No guest prompt — may have gone directly to checkout");
            }
        }
    }

    private void verifyCheckoutPageReached() {
        // Verify we're on the checkout page by URL or page content
        longWait.until(driver -> {
            String url = driver.getCurrentUrl().toLowerCase();
            return url.contains("checkout") || url.contains("order");
        });

        String currentUrl = driver.getCurrentUrl();
        assertTrue(
            currentUrl.toLowerCase().contains("checkout") ||
            currentUrl.toLowerCase().contains("order"),
            "Expected to be on checkout page, but URL was: " + currentUrl
        );

        System.out.println("[STEP 8] ✅ Reached checkout page: " + currentUrl);
        System.out.println("═══════════════════════════════════════════════");
        System.out.println("  TEST COMPLETE — Stopped BEFORE placing order");
        System.out.println("═══════════════════════════════════════════════");

        // Take a screenshot as proof we reached checkout
        takeScreenshot("checkout_reached");
    }

    // ───────────────────────────── Utilities ─────────────────────────────────────

    private void takeScreenshot(String name) {
        try {
            TakesScreenshot ts = (TakesScreenshot) driver;
            byte[] screenshot = ts.getScreenshotAs(OutputType.BYTES);
            java.nio.file.Files.write(
                java.nio.file.Paths.get(System.getProperty("user.dir"), name + ".png"),
                screenshot
            );
            System.out.println("[SCREENSHOT] Saved: " + name + ".png");
        } catch (Exception e) {
            System.out.println("[SCREENSHOT] Failed: " + e.getMessage());
        }
    }
}